SELECT *
FROM contacts;

SELECT first_name AS name
FROM contacts
WHERE contact_id > 300 
ORDER BY first_name DESC;

SELECT COUNT(*) AS "JUMLAH KONTAK" FROM CONTACTS;
SELECT COUNT(*) AS "JUMLAH COUNTRIES" FROM COUNTRIES;
SELECT COUNT(*) AS "JUMLAH CUSTOMERS" FROM CUSTOMERS;
SELECT COUNT(*) AS "JUMLAH EMPLOYEES" FROM EMPLOYEES;
SELECT COUNT(*) AS "JUMLAH INVENTORIES" FROM INVENTORIES;
SELECT COUNT(*) AS "JUMLAH LOCATIONS" FROM LOCATIONS;
SELECT COUNT(*) AS "JUMLAH ORDER_ITEMS" FROM ORDER_ITEMS;
SELECT COUNT(*) AS "JUMLAH ORDERS" FROM ORDERS;
SELECT COUNT(*) AS "JUMLAH PRODUCT_CATEGORIES" FROM PRODUCT_CATEGORIES;
SELECT COUNT(*) AS "JUMLAH PRODUCTS" FROM PRODUCTS;
SELECT COUNT(*) AS "JUMLAH REGIONS" FROM REGIONS;
SELECT COUNT(*) AS "JUMLAH WAREHOUSES" FROM WAREHOUSES;

SELECT WAREHOUSE_NAME FROM WAREHOUSES;


-- 
-- CONTOH 1
SELECT WAREHOUSE_NAME, CITY
FROM WAREHOUSES, LOCATIONS
WHERE WAREHOUSES.LOCATION_ID = LOCATIONS.LOCATION_ID;

-- CONTOH 2
SELECT STATUS
FROM ORDERS;

-- CONTOH 3
SELECT NAME
FROM CUSTOMERS, ORDERS
WHERE CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
AND STATUS = 'Canceled';

--LATIHAN
SELECT name,first_name,last_name
FROM customers,contacts
WHERE contacts.customer_id = customers.customer_id;